packages:
  - apps/*
  - packages/*

overrides:
  '@eslint/plugin-kit@<0.3.4': '>=0.3.4'
  body-parser@>=2.2.0 <2.2.1: '>=2.2.1'
  glob@>=10.2.0 <10.5.0: '>=10.5.0'
  js-yaml@>=4.0.0 <4.1.1: '>=4.1.1'
  jws@<3.2.3: '>=3.2.3'
  node-forge@<1.3.2: '>=1.3.2'
  validator@<13.15.20: '>=13.15.20'
  validator@<13.15.22: '>=13.15.22'
  vite@>=6.0.0 <=6.3.5: '>=6.3.6'
  vite@>=6.0.0 <=6.4.0: '>=6.4.1'
