packages:
  - apps/*
  - packages/*

overrides:
  '@eslint/plugin-kit@<0.3.4': '>=0.3.4'
  '@isaacs/brace-expansion@<=5.0.0': '>=5.0.1'
  ajv@<6.14.0: '>=6.14.0'
  ajv@>=7.0.0-alpha.0 <8.18.0: '>=8.18.0'
  body-parser@>=2.2.0 <2.2.1: '>=2.2.1'
  diff@>=6.0.0 <8.0.3: '>=8.0.3'
  glob@>=10.2.0 <10.5.0: '>=10.5.0'
  h3@<=1.15.4: '>=1.15.5'
  js-yaml@>=4.0.0 <4.1.1: '>=4.1.1'
  jws@<3.2.3: '>=3.2.3'
  lodash-es@>=4.0.0 <=4.17.22: '>=4.17.23'
  lodash@>=4.0.0 <=4.17.22: '>=4.17.23'
  minimatch@<3.1.3: '>=3.1.3'
  minimatch@<3.1.4: '>=3.1.4'
  minimatch@>=10.0.0 <10.2.1: '>=10.2.1'
  minimatch@>=10.0.0 <10.2.3: '>=10.2.3'
  minimatch@>=5.0.0 <5.1.7: '>=5.1.7'
  minimatch@>=5.0.0 <5.1.8: '>=5.1.8'
  minimatch@>=9.0.0 <9.0.6: '>=9.0.6'
  minimatch@>=9.0.0 <9.0.7: '>=9.0.7'
  node-forge@<1.3.2: '>=1.3.2'
  rollup@>=4.0.0 <4.59.0: '>=4.59.0'
  serialize-javascript@<=7.0.2: '>=7.0.3'
  tar@<7.5.7: '>=7.5.7'
  tar@<7.5.8: '>=7.5.8'
  tar@<=7.5.2: '>=7.5.3'
  tar@<=7.5.3: '>=7.5.4'
  validator@<13.15.20: '>=13.15.20'
  validator@<13.15.22: '>=13.15.22'
  vite@>=6.0.0 <=6.3.5: '>=6.3.6'
  vite@>=6.0.0 <=6.4.0: '>=6.4.1'
