services:
  azurite:
    container_name: azurite
    image: mcr.microsoft.com/azure-storage/azurite
    pull_policy: always
    restart: unless-stopped
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    volumes:
      - azurite-data:/data

volumes:
  azurite-data:
    driver: local
